from setuptools import setup, find_packages

setup(
    name="linuxreport",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "beautifulsoup4",
        "cacheout",
        "diskcache",
        "fake_useragent",
        "feedparser",
        "filelock",
        "Flask",
        "Flask_Mobility",
        "geoip2",
        "Jinja2",
        "MarkupSafe",
        "openai",
        "pandas",
        "Pillow",
        "Requests",
        "selenium",
        "sentence_transformers",
        "sqlalchemy",
        "webdriver_manager",
        "Werkzeug",
        "WTForms",
    ],
    author="Keith Curtis",
    author_email="keithcu@gmail.com",
    description="A fast Python aggregation site for Linux, Covid-19, AI, etc. news",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/KeithCu/LinuxReport",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
) 